Clonal tree visualization
immunomind/immunarch pull request #270
Opened 2022-07-21 14:04 UTC by Alexander230

Implementation of visualization trees from repClonalFamily()

2022-07-22 10:29 UTC, MVolobueva requested changes
Bugs:
1. Germline is not outgroup for clonal tree. It needs changes in PHYLIP run with parameter -O. For more details look here: https://evolution.genetics.washington.edu/phylip/doc/dnapars.html
2. Some vertex names in edge list are not listed in vertex data frame. Example code:
```
data("bcrdata")

bcr_data <- bcrdata$data
bcr_data <- bcr_data %>%
  seqCluster(seqDist(bcr_data), .fixed_threshold = 15) %>%
  repGermline(.threads = 2) %>%
  repAlignLineage(.min_lineage_sequences = 4, .align_threads = 2, .nofail = TRUE) %>%
  repClonalFamily(.threads = 2, .nofail = TRUE) 
vis(bcr_data)
```
To improve:
For AP -> add weight for edges in graph from PHYLIP
For MS -> convert weight for edges in nt and aa mutations

2022-08-11 13:58 UTC, MVolobueva submitted a review, later dismissed

2022-08-11 14:59 UTC, MVolobueva commented
Error in calculating aa mutations

2022-08-11 15:12 UTC, Alexander230 commented
Bugs with AA reference frame start and with distances calculation will be fixed in the next PR

2022-08-11 15:12 UTC, merged